### ISSUE TITLE
alternative model for overdispersion

### ISSUE THREAD

**Issue by Schmidtpk** [ImperialCollegeLondon/epidemia#56]
I would argue that a more suitable model for overdispersion depends on the current case load. [For high expected deaths/case counts, overdispersion decreases](https://arxiv.org/abs/2011.04002) (as the sum of many independent overdispersed variables is less overdispersed).

I don't think the current functions allow to implement

Y ~ F(y, y \Psi)

which would be a nice improvement.

**Comment by jscott6** [comment]
Thanks for this - we allow over-dispersion for observations, which are modelled in terms of expected infections. Actual infections are not explicitly modelled, as the number of parameters to sample then increases linearly with the number of simulation periods, and sampling takes much longer.

We do have the option of a quasi-poisson model which, unless I'm mistaken, allows implementing what you ask for:

Y ~ NB(y, y * \Psi) is the same as Y ~ QP(1 / \Psi)

This is because the NB variance y + y * y / (y \Psi) = y * (1 + 1 / \Psi), i.e. is a constant factor above the variance of a Poisson. 

I would also point out that for observations, dispersion will not always decrease as cases rise. For much daily incidence/death data for COVID-19 we observe a lot of intra-week seasonality in reporting rates, for example, which will affect the observation variance.

**Comment by Schmidtpk** [comment]
> This is because the NB variance y + y * y / (y \Psi) = y * (1 + 1 / \Psi), i.e. is a constant factor above the variance of a Poisson.

Great, very helpful. I can't find info on the quasi-poisson implementation, though. Any part of the documentation you could point me to?

The main vignette states 
> epidemia currently supports poisson and negative binomial families. The poisson distribution has no auxiliary parameter,...
which left my thinking there is currently no alternative.

> For much daily incidence/death data for COVID-19 we observe a lot of intra-week seasonality in reporting rates, for example, which will affect the observation variance.

Agreed, but one could argue that this is best modeled with the reporting rate (your alpha, "which represents the probability that any event occuring at time t0+t is actually recorded as an observation").

**Comment by jscott6** [comment]
Sorry for taking a while to get back to you. We've released a new version of epidemia where infections are treated can be treated as latent parameters, which can help account for super-spreading event. This can be done using `latent = TRUE` in the call to `epiinf()`. For more information, please see Section 5.2 [here](https://imperialcollegelondon.github.io/epidemia/articles/model-description.html), and this [vignette](https://imperialcollegelondon.github.io/epidemia/articles/flu.html), which gives a simple example
