### ISSUE TITLE
inference for multiple strains

### ISSUE THREAD

**Issue by andreaskoher** [ImperialCollegeLondon/epidemia#62]
Hi and great package!

end of next week, we will give an introduction to your package at a [workshop](https://events.au.dk/coviddata/conference) and in the run up some researchers raised their interest to infer the reproduction number for multiple strains that exist in parallel within a population. Apparently, there is weekly genome sequence data available for Denmark and I was wondering if this type of inference is already possible with Epidemia.

Many thanks and keep up this great work :)

**Comment by s-mishra** [comment]
Hi @andreaskoher, thanks for your comments. 

So if the aim is to do only transmission advantage not worry about teasing out the advantage seen due to immune escape capabilities of a variant (look at the characterization of gamma, P1, in our [science paper](https://science.sciencemag.org/content/early/2021/04/13/science.abh2644) ), you can look at the code we did for characterizing alpha (B117) in our [nature paper](https://www.nature.com/articles/s41586-021-03470-x). The code for model is available [here](https://github.com/mrc-ide/sarscov2-b.1.1.7/blob/421526ba1196d2a8ffe1a99e196a136b4f6cbec6/transmission_model/models/joint_model.R). Just that you need to adjust it a bit for specific use case depending on the data you have.  

So yes this is very much plausible. But if interest is in characterising delta, which has immune escape capabilities, I will encourage you to look at the code [here](https://github.com/CADDE-CENTRE/Novel-SARS-CoV-2-P1-Lineage-in-Brazil/tree/main/transmission_model) or [here](https://github.com/ImperialCollegeLondon/Delta_Variant_Delhi).
